FROM python:3.11-slim-bullseye AS builder
ENV VIRTUAL_ENV=/opt/venv
ENV CODE_PATH=/source
RUN pip3 install --no-cache-dir poetry==1.8.3
RUN python3 -m venv $VIRTUAL_ENV
WORKDIR $CODE_PATH
COPY /backend/poetry.lock /backend/pyproject.toml ${CODE_PATH}/
RUN python3 -m poetry export --with unix --without test -f requirements.txt | $VIRTUAL_ENV/bin/pip install -r /dev/stdin

FROM python:3.11-slim-bullseye AS run-image
ENV VIRTUAL_ENV=/opt/venv
ENV CODE_PATH=/source
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
COPY --from=builder $VIRTUAL_ENV $VIRTUAL_ENV
COPY /backend ${CODE_PATH}/backend
WORKDIR $CODE_PATH/backend
EXPOSE 8000
ENTRYPOINT ["uvicorn", "--factory", "src.__main__:create_app", "--host", "0.0.0.0", "--port", "8000", "--proxy-headers"]