FROM node:alpine AS build

WORKDIR /source

COPY /frontend/package.json /frontend/package-lock.json ./
RUN npm install
COPY /frontend .
RUN npm run build

FROM nginx:alpine
COPY --from=build /source/dist /usr/share/nginx/html
COPY /frontend/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 5173
CMD ["nginx", "-g", "daemon off;"]